### ISSUE TITLE
Create a view for recording voice memos within a note

### ISSUE THREAD

**Issue by sydneyhauke** [steroid-team/app#140]
Features that we expect:

- Start recording the memo.
- Stop the recording.
- Pause the recording (so that it can be resumed). Maybe this can be merged with the previous feature.
- Replay the recording so far.
- Close the recording view.

It would also be great if the user could move around the recorded memo while recording (go forward and backward, like when you're playing a song).

**Comment by YagoGG** [comment]
@sydneyhauke you might be interested in checking this out: https://github.com/3llomi/RecordView

Maybe it's not what we're looking for, but there might be other interesting options available.
