### ISSUE TITLE
Code Review - Asteroid Notes

### ISSUE THREAD

**Issue by Dietech** [steroid-team/app#186]
This is a code review covering the whole project on the main branch at commit:
https://github.com/steroid-team/app/tree/97ce86f722373c030f1f635d8439523a497a995a

Of course, we don't expect you to change all of your code (some parts of the review can be subjective or arguable anyway), important is that you understand why better alternatives exist.

**Please DO ASK ME / US questions about anything that you do not understand, whether it is by writing a comment below or by sending us a message on Discord/Email.**

**Important : if you try to fix these, don't break your app. I prefer that the app works even if you don't manage to fix everything.**

# Packages

You make good use of packages with regular naming conventions.

* The package structure of the test packages should reflect the structure of your main package.

# Comments

Some classes lack documentation:
* For POJOs (Plain Old Java Objects) like `Note.java`, documentation is not required for getters & setters, however a few lines of documentation at the top of the class and/or constructor would still be useful to quickly understand what this class is used for.
* Some interface implementations `FirebaseFileStorageService.java` lack class documentation. Also some `@Override` are missing.
* The `User.java` interface lacks documentation.
* It would still be useful to have documentation at the top of each classes that are extensions of Android classes, like adapters, custom views, etc...

# Style

* `FBaseUser.java` should be renamed `FirebaseUser.java` so that it matches other classes like `FirebaseDatabase.java` & `FirebaseFileStorageService.java`

Otherwise, the style is clear and consistent.

# Class naming

Nothing to say here, clear and meaningful

# Modularity

* Nice use of `ViewModel` in the `ItemViewActivity.java`, you should also use viewmodels in your other activities.
* `TodoRepository.java` might not be necessary as it does not provide any useful abstraction.

# Models

* `Note.java` does not provide a `toString` and `equals` methods whereas the other data classes do.

# Abstractions

* Very nice use of futures in `FirebaseFileStorageService.java`, however it is made synchronous in its `FirebaseDatabase.java`. This removes the benefits of asynchrony. You should consider modifying the database interface to make use of futures or other asynchronous constructs (even for `void` methods).
* `FirebaseFileStorageService.java` is never used in the app ?
* `ListSelectionActivity.java` is using proprietary code from Firebase UI. You should consider implementing your own or abstracting the code away.
* `MainActivity.java` is using a lot of proprietary code from Firebase. You should abstract that away to be able to test it.
* `MapsActivity.java` has no abstraction for the `GeoCoder` service. Consider creating an abstraction layer to be able to test it.

# Testing

* Consider refactoring the `TodoListTest.java` test class.
* `FBaseUserTest.java` should check that the correct values are returned from `FirebaseAuth`.
* `TodoRepository.java` should have more tests.
* `FirebaseFIleStorageService.java` does not have unit tests ?

# Overall

Your app is well structured and follows a consistent coding convention.

You still miss a few abstractions for various services (geocoder, firebaseauth) which makes your code hard to test. I would also recommend to start using your firebase storage service instead of relying on static hardcoded data.
Finally, if you need help testing Google Maps on Cirrus, I would suggest to post something on Discord so that other students/TAs can help you with that.

Good luck and keep up the good work!

**Comment by YagoGG** [comment]
Closing these as all the points have been addressed (or are no longer applicable due to changes in the app).

Thanks a lot for the super valuable feedback @Dietech @maximilian1064!
