### ISSUE TITLE
Investigate test flakiness

### ISSUE THREAD

**Issue by YagoGG** [steroid-team/app#231]

**Comment by YagoGG** [comment]
**Passing run:** https://cirrus-ci.com/task/5159542049734656
**Failing run:** https://cirrus-ci.com/task/5464218439778304

```
> Task :app:connectedDebugAndroidTest
Starting 44 tests on test(AVD) - 10
com.github.steroidteam.todolist.DrawingFragmentTest > secondButtonWorks[test(AVD) - 10] FAILED 
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 95, 125 and precision: 16, 16' on view 'with id is <com.github.steroidteam.todolist:id/drawing_second_button>'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
```

**Comment by sydneyhauke** [comment]
`com.github.steroidteam.todolist.DrawingFragmentTest > fourthButtonWorks[test(AVD) - 10] FAILED 
	java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.concurrent.CompletableFuture java.util.concurrent.CompletableFuture.thenAccept(java.util.function.Consumer)' on a null object reference
	at com.github.steroidteam.todolist.viewmodel.ListSelectionViewModel.<init>(ListSelectionViewModel.java:23)`

**Comment by shoutizix** [comment]
com.github.steroidteam.todolist.NoteSelectionFragmentTest > cancelRenamingWorks[test(AVD) - 10] �[31mFAILED �[0m
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131820812>[rename_note_suggestion] value: Enter a new title for your Note:
	

com.github.steroidteam.todolist.NoteSelectionFragmentTest > cancelDeleteNoteWorks[test(AVD) - 10] �[31mFAILED �[0m
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131820615>[delete_note_suggestion] value: Are you sure to delete this note?

**Comment by shoutizix** [comment]
com.github.steroidteam.todolist.ListSelectionFragmentTest > cancelDeletionWorks[test(AVD) - 10] �[31mFAILED �[0m
	androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: View is present in the hierarchy: DialogTitle{id=2131361872, res-name=alertTitle, visibility=VISIBLE, width=264, height=25, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@842220c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=24.0, y=18.0, text=Are you sure to delete this to-do?, input-type=0, ime-target=false, has-links=false}
	Expected: is <false>

com.github.steroidteam.todolist.NoteSelectionFragmentTest > cancelDeleteNoteWorks[test(AVD) - 10] �[31mFAILED �[0m
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131886154>[delete_note_suggestion] value: Are you sure to delete this note?

**Comment by shoutizix** [comment]
com.github.steroidteam.todolist.ItemViewFragmentTest > updateTaskWorks[test(AVD) - 10] �[31mFAILED �[0m
	androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 156, 607 and precision: 16, 16' on view 'with id is <com.github.steroidteam.todolist:id/new_task_text>'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)

com.github.steroidteam.todolist.ListSelectionFragmentTest > cantRenameTodoWithoutText[test(AVD) - 10] �[31mFAILED �[0m
	androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: View is present in the hierarchy: EditText{id=2131361873, res-name=alert_dialog_edit_text, visibility=VISIBLE, width=304, height=46, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e5b5cd9, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x1 imeOptions=0x6 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=My todo list label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], x=0.0, y=0.0, text=, hint=My todo list, input-type=1, ime-target=false, has-links=false}
	Expected: is <false>

**Comment by shoutizix** [comment]
com.github.steroidteam.todolist.ListSelectionFragmentTest > deleteTodoWorks[test(AVD) - 10] 
FAILED 
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131886155>[delete_todo_suggestion] value: Are you sure to delete this to-do?
com.github.steroidteam.todolist.NoteSelectionFragmentTest > cancelRenamingWorks[test(AVD) - 10] 
FAILED 
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131886353>[rename_note_suggestion] value: Enter a new title for your Note:
